//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class altYoneticiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public altYoneticiler()
        {
            this.personeller = new HashSet<personeller>();
        }
    
        public int a_id { get; set; }
        public string a_kullanici_adi { get; set; }
        public string a_kullanici_sifre { get; set; }
        public string a_adi_soyadi { get; set; }
        public string a_email { get; set; }
        public Nullable<int> a_aktiflik { get; set; }
        public Nullable<System.DateTime> a_ise_giris_tarihi { get; set; }
        public Nullable<System.DateTime> a_olusturulma_tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personeller> personeller { get; set; }
    }
}
