//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class izinTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public izinTurleri()
        {
            this.izinler = new HashSet<izinler>();
        }
    
        public int id { get; set; }
        public string izin_adi { get; set; }
        public Nullable<int> izin_aktiflik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izinler> izinler { get; set; }
    }
}
