//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinUygulamasi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class izinApp2Entities : DbContext
    {
        public izinApp2Entities()
            : base("name=izinApp2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<altYoneticiler> altYoneticiler { get; set; }
        public virtual DbSet<izinler> izinler { get; set; }
        public virtual DbSet<izinTurleri> izinTurleri { get; set; }
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<sysAdmin> sysAdmin { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
