//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personeller()
        {
            this.izinler = new HashSet<izinler>();
        }
    
        public int p_id { get; set; }
        public string p_kullanici_adi { get; set; }
        public string p_kullanici_sifre { get; set; }
        public string p_adi_soyadi { get; set; }
        public string p_email { get; set; }
        public Nullable<int> p_aktiflik { get; set; }
        public Nullable<System.DateTime> p_ise_giris_tarihi { get; set; }
        public Nullable<System.DateTime> p_olusturulma_tarihi { get; set; }
        public Nullable<int> altYoneticiId { get; set; }
    
        public virtual altYoneticiler altYoneticiler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izinler> izinler { get; set; }
    }
}
